enum ActionEnum {
    SET_REGISTRATIONS = "SET_REGISTRATIONS",
    ADD_REGISTRATION = "ADD_REGISTRATIONS",
    UPDATE_REGISTRATION = "UPDATE_REGISTRATION",
    DELETE_REGISTRATION = "DELETE_REGISTRATION",
    SET_STATUS = "SET_STATUS",
}

export default ActionEnum;